### ISSUE TITLE
CSS Missing in production

### ISSUE THREAD

**Issue by RuneClaeys** [DarkC0der11/vue-skeletor#1]
I'm using vue-skeletor by having it registered as a global component in the main.ts file. When I run `npm run serve`, the skeleton is show properly. But when I run `npm run build`, and than deploy or serve the dist folder locally, no skeletons are shown. 

I tried to inspect the elements and all of their heights are 0 and when I compare the css between build and a run serve, they are missing classes for `--text`. Maybe I'm importing the wrong css file or in the wrong place?

```
// main.ts

import { createApp } from 'vue';
import App from './App.vue';

import { Skeletor } from 'vue-skeletor';
import 'vue-skeletor/dist/vue-skeletor.css';

const app = createApp(App);
app.component(Skeletor.name, Skeletor);
app.mount('#app');
```

// css applied to element upon inspecting

```
element.style {
    width: 61%;
}
.vue-skeletor[data-v-67fa99f4] {
    min-height: 16px;
}
.vue-skeletor[data-v-67fa99f4] {
    border-radius: 3px;
}
.vue-skeletor {
    min-height: 16px;
}
.vue-skeletor {
    border-radius: 3px;
}
.vue-skeletor {
    min-height: 16px;
}
.vue-skeletor {
    border-radius: 3px;
}
.vue-skeletor {
    min-height: 16px;
}
.vue-skeletor {
    border-radius: 3px;
}
html, html * {
    scrollbar-color: #039adb #f6f6f6;
    scrollbar-width: thin;
}
*, ::after, ::before {
    box-sizing: border-box;
}
```

```
// package.json
"vue": "^3.0.0",
"vue-skeletor": "^1.0.6",
```

**Comment by Lilja** [comment]
I'm investigating weird issues running this. Perhaps this is related?

Is it just me, or is the css file wrong? I'm fairly sure that nested syntax isn't supported. Here is my disted file. You can see that .vue-skeletor is nesting alot of different css selectors. Did the compilation really go through?

cc @DarkC0der11 

<details>
<summary>Click to expand</summary>

```css
.vue-skeletor {
  position: relative;
  overflow: hidden;
  background-color: rgba(0, 0, 0, 0.12); }
  .vue-skeletor:not(.vue-skeletor--shimmerless):after {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    transform: translateX(-100%);
    background-image: linear-gradient(90deg, rgba(255, 255, 255, 0), rgba(255, 255, 255, 0.3), rgba(37, 22, 22, 0));
    animation: shimmer 1.5s infinite;
    content: ''; }
  .vue-skeletor--rect, .vue-skeletor--circle {
    display: block; }
  .vue-skeletor--circle {
    border-radius: 50%; }
  .vue-skeletor--pill, .vue-skeletor--text {
    border-radius: 9999px; }
  .vue-skeletor--text {
    line-height: 1;
    display: inline-block;
    width: 100%;
    height: inherit;
    vertical-align: middle;
    top: -1px; }

@keyframes shimmer {
  100% {
    transform: translateX(100%); } }


```

</details>
